const std = @import("std");
const thread = std.Thread;


const Measure = struct {
    city: []const u8,
    temperature: f32,
};
 
//var m_mutex: thread.Mutex = undefined;
var Measures = [_]Measure{
                     Measure{.city = "Abha", .temperature = 18.0},
                     Measure{.city = "Abidjan", .temperature = 26.0},
                     Measure{.city = "Abéché", .temperature = 29.4},
                     Measure{.city = "Accra", .temperature = 26.4},
                     Measure{.city = "Addis Ababa", .temperature = 16.0},
                     Measure{.city = "Adelaide", .temperature = 17.3},
                     Measure{.city = "Aden", .temperature = 29.1},
                     Measure{.city = "Ahvaz", .temperature = 25.4},
                     Measure{.city = "Albuquerque", .temperature = 14.0},
                     Measure{.city = "Alexandra", .temperature = 11.0},
                     Measure{.city = "Alexandria", .temperature = 20.0},
                     Measure{.city = "Algiers", .temperature = 18.2},
                     Measure{.city = "Alice Springs", .temperature = 21.0},
                     Measure{.city = "Almaty", .temperature = 10.0},
                     Measure{.city = "Amsterdam", .temperature = 10.2},
                     Measure{.city = "Anadyr", .temperature = -6.9},
                     Measure{.city = "Anchorage", .temperature = 2.8},
                     Measure{.city = "Andorra la Vella", .temperature = 9.8},
                     Measure{.city = "Ankara", .temperature = 12.0},
                     Measure{.city = "Antananarivo", .temperature = 17.9},
                     Measure{.city = "Antsiranana", .temperature = 25.2},
                     Measure{.city = "Arkhangelsk", .temperature = 1.3},
                     Measure{.city = "Ashgabat", .temperature = 17.1},
                     Measure{.city = "Asmara", .temperature = 15.6},
                     Measure{.city = "Assab", .temperature = 30.5},
                     Measure{.city = "Astana", .temperature = 3.5},
                     Measure{.city = "Athens", .temperature = 19.2},
                     Measure{.city = "Atlanta", .temperature = 17.0},
                     Measure{.city = "Auckland", .temperature = 15.2},
                     Measure{.city = "Austin", .temperature = 20.7},
                     Measure{.city = "Baghdad", .temperature = 22.77},
                     Measure{.city = "Baguio", .temperature = 19.5},
                     Measure{.city = "Baku", .temperature = 15.1},
                     Measure{.city = "Baltimore", .temperature = 13.1},
                     Measure{.city = "Bamako", .temperature = 27.8},
                     Measure{.city = "Bangkok", .temperature = 28.6},
                     Measure{.city = "Bangui", .temperature = 26.0},
                     Measure{.city = "Banjul", .temperature = 26.0},
                     Measure{.city = "Barcelona", .temperature = 18.2},
                     Measure{.city = "Batumi", .temperature = 14.0},
                     Measure{.city = "Beijing", .temperature = 12.9},
                     Measure{.city = "Beirut", .temperature = 20.9},
                     Measure{.city = "Belgrade", .temperature = 12.5},
                     Measure{.city = "Belize City", .temperature = 26.7},
                     Measure{.city = "Benghazi", .temperature = 19.9},
                     Measure{.city = "Bergen", .temperature = 7.7},
                     Measure{.city = "Berlin", .temperature = 10.3},
                     Measure{.city = "Bilbao", .temperature = 14.7},
                     Measure{.city = "Birao", .temperature = 26.5},
                     Measure{.city = "Bishkek", .temperature = 11.3},
                     Measure{.city = "Bissau", .temperature = 27.0},
                     Measure{.city = "Blantyre", .temperature = 22.2},
                     Measure{.city = "Bloemfontein", .temperature = 15.6},
                     Measure{.city = "Boise", .temperature = 11.4},
                     Measure{.city = "Bordeaux", .temperature = 14.2},
                     Measure{.city = "Bosaso", .temperature = 30.0},
                     Measure{.city = "Boston", .temperature = 10.9},
                     Measure{.city = "Bouaké", .temperature = 26.0},
                     Measure{.city = "Bratislava", .temperature = 10.5},
                     Measure{.city = "Brazzaville", .temperature = 25.0},
                     Measure{.city = "Bridgetown", .temperature = 27.0},
                     Measure{.city = "Brisbane", .temperature = 21.4},
                     Measure{.city = "Brussels", .temperature = 10.5},
                     Measure{.city = "Bucharest", .temperature = 10.8},
                     Measure{.city = "Budapest", .temperature = 11.3},
                     Measure{.city = "Bujumbura", .temperature = 23.8},
                     Measure{.city = "Bulawayo", .temperature = 18.9},
                     Measure{.city = "Burnie", .temperature = 13.1},
                     Measure{.city = "Busan", .temperature = 15.0},
                     Measure{.city = "Cabo San Lucas", .temperature = 23.9},
                     Measure{.city = "Cairns", .temperature = 25.0},
                     Measure{.city = "Cairo", .temperature = 21.4},
                     Measure{.city = "Calgary", .temperature = 4.4},
                     Measure{.city = "Canberra", .temperature = 13.1},
                     Measure{.city = "Cape Town", .temperature = 16.2},
                     Measure{.city = "Changsha", .temperature = 17.4},
                     Measure{.city = "Charlotte", .temperature = 16.1},
                     Measure{.city = "Chiang Mai", .temperature = 25.8},
                     Measure{.city = "Chicago", .temperature = 9.8},
                     Measure{.city = "Chihuahua", .temperature = 18.6},
                     Measure{.city = "Chișinău", .temperature = 10.2},
                     Measure{.city = "Chittagong", .temperature = 25.9},
                     Measure{.city = "Chongqing", .temperature = 18.6},
                     Measure{.city = "Christchurch", .temperature = 12.2},
                     Measure{.city = "City of San Marino", .temperature = 11.8},
                     Measure{.city = "Colombo", .temperature = 27.4},
                     Measure{.city = "Columbus", .temperature = 11.7},
                     Measure{.city = "Conakry", .temperature = 26.4},
                     Measure{.city = "Copenhagen", .temperature = 9.1},
                     Measure{.city = "Cotonou", .temperature = 27.2},
                     Measure{.city = "Cracow", .temperature = 9.3},
                     Measure{.city = "Da Lat", .temperature = 17.9},
                     Measure{.city = "Da Nang", .temperature = 25.8},
                     Measure{.city = "Dakar", .temperature = 24.0},
                     Measure{.city = "Dallas", .temperature = 19.0},
                     Measure{.city = "Damascus", .temperature = 17.0},
                     Measure{.city = "Dampier", .temperature = 26.4},
                     Measure{.city = "Dar es Salaam", .temperature = 25.8},
                     Measure{.city = "Darwin", .temperature = 27.6},
                     Measure{.city = "Denpasar", .temperature = 23.7},
                     Measure{.city = "Denver", .temperature = 10.4},
                     Measure{.city = "Detroit", .temperature = 10.0},
                     Measure{.city = "Dhaka", .temperature = 25.9},
                     Measure{.city = "Dikson", .temperature = -11.1},
                     Measure{.city = "Dili", .temperature = 26.6},
                     Measure{.city = "Djibouti", .temperature = 29.9},
                     Measure{.city = "Dodoma", .temperature = 22.7},
                     Measure{.city = "Dolisie", .temperature = 24.0},
                     Measure{.city = "Douala", .temperature = 26.7},
                     Measure{.city = "Dubai", .temperature = 26.9},
                     Measure{.city = "Dublin", .temperature = 9.8},
                     Measure{.city = "Dunedin", .temperature = 11.1},
                     Measure{.city = "Durban", .temperature = 20.6},
                     Measure{.city = "Dushanbe", .temperature = 14.7},
                     Measure{.city = "Edinburgh", .temperature = 9.3},
                     Measure{.city = "Edmonton", .temperature = 4.2},
                     Measure{.city = "El Paso", .temperature = 18.1},
                     Measure{.city = "Entebbe", .temperature = 21.0},
                     Measure{.city = "Erbil", .temperature = 19.5},
                     Measure{.city = "Erzurum", .temperature = 5.1},
                     Measure{.city = "Fairbanks", .temperature = -2.3},
                     Measure{.city = "Fianarantsoa", .temperature = 17.9},
                     Measure{.city = "Flores, Petén", .temperature = 26.4},
                     Measure{.city = "Frankfurt", .temperature = 10.6},
                     Measure{.city = "Fresno", .temperature = 17.9},
                     Measure{.city = "Fukuoka", .temperature = 17.0},
                     Measure{.city = "Gabès", .temperature = 19.5},
                     Measure{.city = "Gaborone", .temperature = 21.0},
                     Measure{.city = "Gagnoa", .temperature = 26.0},
                     Measure{.city = "Gangtok", .temperature = 15.2},
                     Measure{.city = "Garissa", .temperature = 29.3},
                     Measure{.city = "Garoua", .temperature = 28.3},
                     Measure{.city = "George Town", .temperature = 27.9},
                     Measure{.city = "Ghanzi", .temperature = 21.4},
                     Measure{.city = "Gjoa Haven", .temperature = -14.4},
                     Measure{.city = "Guadalajara", .temperature = 20.9},
                     Measure{.city = "Guangzhou", .temperature = 22.4},
                     Measure{.city = "Guatemala City", .temperature = 20.4},
                     Measure{.city = "Halifax", .temperature = 7.5},
                     Measure{.city = "Hamburg", .temperature = 9.7},
                     Measure{.city = "Hamilton", .temperature = 13.8},
                     Measure{.city = "Hanga Roa", .temperature = 20.5},
                     Measure{.city = "Hanoi", .temperature = 23.6},
                     Measure{.city = "Harare", .temperature = 18.4},
                     Measure{.city = "Harbin", .temperature = 5.0},
                     Measure{.city = "Hargeisa", .temperature = 21.7},
                     Measure{.city = "Hat Yai", .temperature = 27.0},
                     Measure{.city = "Havana", .temperature = 25.2},
                     Measure{.city = "Helsinki", .temperature = 5.9},
                     Measure{.city = "Heraklion", .temperature = 18.9},
                     Measure{.city = "Hiroshima", .temperature = 16.3},
                     Measure{.city = "Ho Chi Minh City", .temperature = 27.4},
                     Measure{.city = "Hobart", .temperature = 12.7},
                     Measure{.city = "Hong Kong", .temperature = 23.3},
                     Measure{.city = "Honiara", .temperature = 26.5},
                     Measure{.city = "Honolulu", .temperature = 25.4},
                     Measure{.city = "Houston", .temperature = 20.8},
                     Measure{.city = "Ifrane", .temperature = 11.4},
                     Measure{.city = "Indianapolis", .temperature = 11.8},
                     Measure{.city = "Iqaluit", .temperature = -9.3},
                     Measure{.city = "Irkutsk", .temperature = 1.0},
                     Measure{.city = "Istanbul", .temperature = 13.9},
                     Measure{.city = "İzmir", .temperature = 17.9},
                     Measure{.city = "Jacksonville", .temperature = 20.3},
                     Measure{.city = "Jakarta", .temperature = 26.7},
                     Measure{.city = "Jayapura", .temperature = 27.0},
                     Measure{.city = "Jerusalem", .temperature = 18.3},
                     Measure{.city = "Johannesburg", .temperature = 15.5},
                     Measure{.city = "Jos", .temperature = 22.8},
                     Measure{.city = "Juba", .temperature = 27.8},
                     Measure{.city = "Kabul", .temperature = 12.1},
                     Measure{.city = "Kampala", .temperature = 20.0},
                     Measure{.city = "Kandi", .temperature = 27.7},
                     Measure{.city = "Kankan", .temperature = 26.5},
                     Measure{.city = "Kano", .temperature = 26.4},
                     Measure{.city = "Kansas City", .temperature = 12.5},
                     Measure{.city = "Karachi", .temperature = 26.0},
                     Measure{.city = "Karonga", .temperature = 24.4},
                     Measure{.city = "Kathmandu", .temperature = 18.3},
                     Measure{.city = "Khartoum", .temperature = 29.9},
                     Measure{.city = "Kingston", .temperature = 27.4},
                     Measure{.city = "Kinshasa", .temperature = 25.3},
                     Measure{.city = "Kolkata", .temperature = 26.7},
                     Measure{.city = "Kuala Lumpur", .temperature = 27.3},
                     Measure{.city = "Kumasi", .temperature = 26.0},
                     Measure{.city = "Kunming", .temperature = 15.7},
                     Measure{.city = "Kuopio", .temperature = 3.4},
                     Measure{.city = "Kuwait City", .temperature = 25.7},
                     Measure{.city = "Kyiv", .temperature = 8.4},
                     Measure{.city = "Kyoto", .temperature = 15.8},
                     Measure{.city = "La Ceiba", .temperature = 26.2},
                     Measure{.city = "La Paz", .temperature = 23.7},
                     Measure{.city = "Lagos", .temperature = 26.8},
                     Measure{.city = "Lahore", .temperature = 24.3},
                     Measure{.city = "ity", .temperature = 23.7},
                     Measure{.city = "Lake Tekapo", .temperature = 8.7},
                     Measure{.city = "Las Palmas de Gran Canaria", .temperature = 21.2},
                     Measure{.city = "Las Vegas", .temperature = 20.3},
                     Measure{.city = "Launceston", .temperature = 13.1},
                     Measure{.city = "Lhasa", .temperature = 7.6},
                     Measure{.city = "Libreville", .temperature = 25.9},
                     Measure{.city = "Lisbon", .temperature = 17.5},
                     Measure{.city = "Livingstone", .temperature = 21.8},
                     Measure{.city = "Ljubljana", .temperature = 10.9},
                     Measure{.city = "Lodwar", .temperature = 29.3},
                     Measure{.city = "Lomé", .temperature = 26.9},
                     Measure{.city = "London", .temperature = 11.3},
                     Measure{.city = "Los Angeles", .temperature = 18.6},
                     Measure{.city = "Louisville", .temperature = 13.9},
                     Measure{.city = "Luanda", .temperature = 25.8},
                     Measure{.city = "Lubumbashi", .temperature = 20.8},
                     Measure{.city = "Lusaka", .temperature = 19.9},
                     Measure{.city = "Luxembourg City", .temperature = 9.3},
                     Measure{.city = "Lviv", .temperature = 7.8},
                     Measure{.city = "Lyon", .temperature = 12.5},
                     Measure{.city = "Madrid", .temperature = 15.0},
                     Measure{.city = "Mahajanga", .temperature = 26.3},
                     Measure{.city = "Makassar", .temperature = 26.7},
                     Measure{.city = "Makurdi", .temperature = 26.0},
                     Measure{.city = "Malabo", .temperature = 26.3},
                     Measure{.city = "Malé", .temperature = 28.0},
                     Measure{.city = "Managua", .temperature = 27.3},
                     Measure{.city = "Manama", .temperature = 26.5},
                     Measure{.city = "Mandalay", .temperature = 28.0},
                     Measure{.city = "Mango", .temperature = 28.1},
                     Measure{.city = "Manila", .temperature = 28.4},
                     Measure{.city = "Maputo", .temperature = 22.8},
                     Measure{.city = "Marrakesh", .temperature = 19.6},
                     Measure{.city = "Marseille", .temperature = 15.8},
                     Measure{.city = "Maun", .temperature = 22.4},
                     Measure{.city = "Medan", .temperature = 26.5},
                     Measure{.city = "Mek'ele", .temperature = 22.7},
                     Measure{.city = "Melbourne", .temperature = 15.1},
                     Measure{.city = "Memphis", .temperature = 17.2},
                     Measure{.city = "Mexicali", .temperature = 23.1},
                     Measure{.city = "Mexico City", .temperature = 17.5},
                     Measure{.city = "Miami", .temperature = 24.9},
                     Measure{.city = "Milan", .temperature = 13.0},
                     Measure{.city = "Milwaukee", .temperature = 8.9},
                     Measure{.city = "Minneapolis", .temperature = 7.8},
                     Measure{.city = "Minsk", .temperature = 6.7},
                     Measure{.city = "Mogadishu", .temperature = 27.1},
                     Measure{.city = "Mombasa", .temperature = 26.3},
                     Measure{.city = "Monaco", .temperature = 16.4},
                     Measure{.city = "Moncton", .temperature = 6.1},
                     Measure{.city = "Monterrey", .temperature = 22.3},
                     Measure{.city = "Montreal", .temperature = 6.8},
                     Measure{.city = "Moscow", .temperature = 5.8},
                     Measure{.city = "Mumbai", .temperature = 27.1},
                     Measure{.city = "Murmansk", .temperature = 0.6},
                     Measure{.city = "Muscat", .temperature = 28.0},
                     Measure{.city = "Mzuzu", .temperature = 17.7},
                     Measure{.city = "N'Djamena", .temperature = 28.3},
                     Measure{.city = "Naha", .temperature = 23.1},
                     Measure{.city = "Nairobi", .temperature = 17.8},
                     Measure{.city = "Nakhon Ratchasima", .temperature = 27.3},
                     Measure{.city = "Napier", .temperature = 14.6},
                     Measure{.city = "Napoli", .temperature = 15.9},
                     Measure{.city = "Nashville", .temperature = 15.4},
                     Measure{.city = "Nassau", .temperature = 24.6},
                     Measure{.city = "Ndola", .temperature = 20.3},
                     Measure{.city = "New Delhi", .temperature = 25.0},
                     Measure{.city = "New Orleans", .temperature = 20.7},
                     Measure{.city = "New York City", .temperature = 12.9},
                     Measure{.city = "Ngaoundéré", .temperature = 22.0},
                     Measure{.city = "Niamey", .temperature = 29.3},
                     Measure{.city = "Nicosia", .temperature = 19.7},
                     Measure{.city = "Niigata", .temperature = 13.9},
                     Measure{.city = "Nouadhibou", .temperature = 21.3},
                     Measure{.city = "Nouakchott", .temperature = 25.7},
                     Measure{.city = "Novosibirsk", .temperature = 1.7},
                     Measure{.city = "Nuuk", .temperature = -1.4},
                     Measure{.city = "Odienné", .temperature = 26.0},
                     Measure{.city = "Oklahoma City", .temperature = 15.9},
                     Measure{.city = "Omaha", .temperature = 10.6},
                     Measure{.city = "Oranjestad", .temperature = 28.1},
                     Measure{.city = "Oslo", .temperature = 5.7},
                     Measure{.city = "Ottawa", .temperature = 6.6},
                     Measure{.city = "Ouagadougou", .temperature = 28.3},
                     Measure{.city = "Ouahigouya", .temperature = 28.6},
                     Measure{.city = "Ouarzazate", .temperature = 18.9},
                     Measure{.city = "Oulu", .temperature = 2.7},
                     Measure{.city = "Palembang", .temperature = 27.3},
                     Measure{.city = "Palermo", .temperature = 18.5},
                     Measure{.city = "Palm Springs", .temperature = 24.5},
                     Measure{.city = "Palmerston North", .temperature = 13.2},
                     Measure{.city = "Panama City", .temperature = 28.0},
                     Measure{.city = "Parakou", .temperature = 26.8},
                     Measure{.city = "Paris", .temperature = 12.3},
                     Measure{.city = "Perth", .temperature = 18.7},
                     Measure{.city = "Petropavlovsk-Kamchatsky", .temperature = 1.9},
                     Measure{.city = "Philadelphia", .temperature = 13.2},
                     Measure{.city = "Phnom Penh", .temperature = 28.3},
                     Measure{.city = "Phoenix", .temperature = 23.9},
                     Measure{.city = "Pittsburgh", .temperature = 10.8},
                     Measure{.city = "Podgorica", .temperature = 15.3},
                     Measure{.city = "Pointe-Noire", .temperature = 26.1},
                     Measure{.city = "Pontianak", .temperature = 27.7},
                     Measure{.city = "Port Moresby", .temperature = 26.9},
                     Measure{.city = "Port Sudan", .temperature = 28.4},
                     Measure{.city = "Port Vila", .temperature = 24.3},
                     Measure{.city = "Port-Gentil", .temperature = 26.0},
                     Measure{.city = "Portland (OR)", .temperature = 12.4},
                     Measure{.city = "Porto", .temperature = 15.7},
                     Measure{.city = "Prague", .temperature = 8.4},
                     Measure{.city = "Praia", .temperature = 24.4},
                     Measure{.city = "Pretoria", .temperature = 18.2},
                     Measure{.city = "Pyongyang", .temperature = 10.8},
                     Measure{.city = "Rabat", .temperature = 17.2},
                     Measure{.city = "Rangpur", .temperature = 24.4},
                     Measure{.city = "Reggane", .temperature = 28.3},
                     Measure{.city = "Reykjavík", .temperature = 4.3},
                     Measure{.city = "Riga", .temperature = 6.2},
                     Measure{.city = "Riyadh", .temperature = 26.0},
                     Measure{.city = "Rome", .temperature = 15.2},
                     Measure{.city = "Roseau", .temperature = 26.2},
                     Measure{.city = "Rostov-on-Don", .temperature = 9.9},
                     Measure{.city = "Sacramento", .temperature = 16.3},
                     Measure{.city = "Saint Petersburg", .temperature = 5.8},
                     Measure{.city = "Saint-Pierre", .temperature = 5.7},
                     Measure{.city = "Salt Lake City", .temperature = 11.6},
                     Measure{.city = "San Antonio", .temperature = 20.8},
                     Measure{.city = "San Diego", .temperature = 17.8},
                     Measure{.city = "San Francisco", .temperature = 14.6},
                     Measure{.city = "San Jose", .temperature = 16.4},
                     Measure{.city = "San José", .temperature = 22.6},
                     Measure{.city = "San Juan", .temperature = 27.2},
                     Measure{.city = "San Salvador", .temperature = 23.1},
                     Measure{.city = "Sana'a", .temperature = 20.0},
                     Measure{.city = "Santo Domingo", .temperature = 25.9},
                     Measure{.city = "Sapporo", .temperature = 8.9},
                     Measure{.city = "Sarajevo", .temperature = 10.1},
                     Measure{.city = "Saskatoon", .temperature = 3.3},
                     Measure{.city = "Seattle", .temperature = 11.3},
                     Measure{.city = "Ségou", .temperature = 28.0},
                     Measure{.city = "Seoul", .temperature = 12.5},
                     Measure{.city = "Seville", .temperature = 19.2},
                     Measure{.city = "Shanghai", .temperature = 16.7},
                     Measure{.city = "Singapore", .temperature = 27.0},
                     Measure{.city = "Skopje", .temperature = 12.4},
                     Measure{.city = "Sochi", .temperature = 14.2},
                     Measure{.city = "Sofia", .temperature = 10.6},
                     Measure{.city = "Sokoto", .temperature = 28.0},
                     Measure{.city = "Split", .temperature = 16.1},
                     Measure{.city = "St. John's", .temperature = 5.0},
                     Measure{.city = "St. Louis", .temperature = 13.9},
                     Measure{.city = "Stockholm", .temperature = 6.6},
                     Measure{.city = "Surabaya", .temperature = 27.1},
                     Measure{.city = "Suva", .temperature = 25.6},
                     Measure{.city = "Suwałki", .temperature = 7.2},
                     Measure{.city = "Sydney", .temperature = 17.7},
                     Measure{.city = "Tabora", .temperature = 23.0},
                     Measure{.city = "Tabriz", .temperature = 12.6},
                     Measure{.city = "Taipei", .temperature = 23.0},
                     Measure{.city = "Tallinn", .temperature = 6.4},
                     Measure{.city = "Tamale", .temperature = 27.9},
                     Measure{.city = "Tamanrasset", .temperature = 21.7},
                     Measure{.city = "Tampa", .temperature = 22.9},
                     Measure{.city = "Tashkent", .temperature = 14.8},
                     Measure{.city = "Tauranga", .temperature = 14.8},
                     Measure{.city = "Tbilisi", .temperature = 12.9},
                     Measure{.city = "Tegucigalpa", .temperature = 21.7},
                     Measure{.city = "Tehran", .temperature = 17.0},
                     Measure{.city = "Tel Aviv", .temperature = 20.0},
                     Measure{.city = "Thessaloniki", .temperature = 16.0},
                     Measure{.city = "Thiès", .temperature = 24.0},
                     Measure{.city = "Tijuana", .temperature = 17.8},
                     Measure{.city = "Timbuktu", .temperature = 28.0},
                     Measure{.city = "Tirana", .temperature = 15.2},
                     Measure{.city = "Toamasina", .temperature = 23.4},
                     Measure{.city = "Tokyo", .temperature = 15.4},
                     Measure{.city = "Toliara", .temperature = 24.1},
                     Measure{.city = "Toluca", .temperature = 12.4},
                     Measure{.city = "Toronto", .temperature = 9.4},
                     Measure{.city = "Tripoli", .temperature = 20.0},
                     Measure{.city = "Tromsø", .temperature = 2.9},
                     Measure{.city = "Tucson", .temperature = 20.9},
                     Measure{.city = "Tunis", .temperature = 18.4},
                     Measure{.city = "Ulaanbaatar", .temperature = -0.4},
                     Measure{.city = "Upington", .temperature = 20.4},
                     Measure{.city = "Ürümqi", .temperature = 7.4},
                     Measure{.city = "Vaduz", .temperature = 10.1},
                     Measure{.city = "Valencia", .temperature = 18.3},
                     Measure{.city = "Valletta", .temperature = 18.8},
                     Measure{.city = "Vancouver", .temperature = 10.4},
                     Measure{.city = "Veracruz", .temperature = 25.4},
                     Measure{.city = "Vienna", .temperature = 10.4},
                     Measure{.city = "Vientiane", .temperature = 25.9},
                     Measure{.city = "Villahermosa", .temperature = 27.1},
                     Measure{.city = "Vilnius", .temperature = 6.0},
                     Measure{.city = "Virginia Beach", .temperature = 15.8},
                     Measure{.city = "Vladivostok", .temperature = 4.9},
                     Measure{.city = "Warsaw", .temperature = 8.5},
                     Measure{.city = "Washington, D.C.", .temperature = 14.6},
                     Measure{.city = "Wau", .temperature = 27.8},
                     Measure{.city = "Wellington", .temperature = 12.9},
                     Measure{.city = "Whitehorse", .temperature = -0.1},
                     Measure{.city = "Wichita", .temperature = 13.9},
                     Measure{.city = "Willemstad", .temperature = 28.0},
                     Measure{.city = "Winnipeg", .temperature = 3.0},
                     Measure{.city = "Wrocław", .temperature = 9.6},
                     Measure{.city = "Xi'an", .temperature = 14.1},
                     Measure{.city = "Yakutsk", .temperature = -8.8},
                     Measure{.city = "Yangon", .temperature = 27.5},
                     Measure{.city = "Yaoundé", .temperature = 23.8},
                     Measure{.city = "Yellowknife", .temperature = -4.3},
                     Measure{.city = "Yerevan", .temperature = 12.4},
                     Measure{.city = "Yinchuan", .temperature = 9.0},
                     Measure{.city = "Zagreb", .temperature = 10.7},
                     Measure{.city = "Zanzibar City", .temperature = 26.0},
                     Measure{.city = "Zürich", .temperature = 9.3}};


const COUNTER = 1_000_000;


fn set_rand_temp(measure: *Measure) void {
    const f = std.crypto.random.float(f32);
    const i = @mod(std.crypto.random.int(i32), @as(i32, 100));
    measure.temperature = @as(f32, @floatFromInt(i)) + f;
}

//var counter: u64 = 0;

fn write_measure(writer: *std.fs.File.Writer, counter: *u64) void {
    while(counter.* < COUNTER / 4) {
        for(&Measures) |*m| {
            set_rand_temp(m);
            writer.interface.print("{s};{d:.1}\n", .{m.city, m.temperature}) catch |err| {
                std.debug.print("{any}\n", .{err});
            };
            //@atomicStore(u64, &counter, @atomicLoad(u64, &counter, .monotonic) + 1, .monotonic);
            // _ = @atomicRmw(u64, &counter, .Add, 1, .monotonic);
            counter.* += 1;
        }
    }
    writer.interface.flush() catch |err| {
        std.debug.print("{any}\n", .{err});
    };
}

pub fn main() !void {
    var buf: [4096]u8 = undefined;

    const f = try std.fs.cwd().createFile("process.txt", .{});
    defer f.close();
    var f_writer = f.writer(&buf);

    var counters: [4]u64 = .{0} ** 4;
    const threads: [4]thread = .{
        try thread.spawn(.{.allocator = std.heap.page_allocator}, write_measure, .{&f_writer, &counters[0]}),
        try thread.spawn(.{.allocator = std.heap.page_allocator}, write_measure, .{&f_writer, &counters[1]}),
        try thread.spawn(.{.allocator = std.heap.page_allocator}, write_measure, .{&f_writer, &counters[2]}),
        try thread.spawn(.{.allocator = std.heap.page_allocator}, write_measure, .{&f_writer, &counters[3]}),
    };

    for(threads) |t| {
        t.join();
    }

    // var pool: std.Thread.Pool = undefined;
    // try pool.init(.{.n_jobs = 4, .allocator = std.heap.page_allocator});
    // defer pool.deinit();
    // try pool.spawn(write_measure, .{&f_writer});

    // var counter: u64 = 0;
    // while(counter < COUNTER) {
    //     for(0..Measures.len) |i| {
    //         set_rand_temp(&Measures[i]);
    //         try f_writer.interface.print("{s};{d:.1}\n", .{Measures[i].city, Measures[i].temperature});
    //         counter += 1;
    //     }
    // }
    try f_writer.interface.flush();
    
}
